### ISSUE TITLE
Support for the Lord of the Rings Mod: Bringing Middle-earth to Minecraft

### ISSUE THREAD

**Issue by joelzierke** [Ted80-Minecraft-Mods/Realistic-World-Gen#1]
I noticed that the Lord of the Rings mod is mentioned as uncompatible, but someday will it be possible for your AWESOME terrain gen to work in Middle-earth? The author of the Lord of the Rings mod does have cool terrain already, but this would be another step up from that.

**Comment by KuroNeko87** [comment]
I would say no to this, It would negate Mevans' hard work in creating a worldgen that resembles middle earth. that's why no matter how many new games you start, the map is the same. some stuff changes like hills/trees but it mostly stays the same.

This is also the same reason why Mevans coded his biomes in a way that doesn't get messed with by other mods.

**Comment by ted80** [comment]
it's also impossible to combine 2 world generators

**Comment by joelzierke** [comment]
Alright, that makes sense. Thanks.
